services:
  app:
    build: .
    ports:
      - "7860:7860"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
       - HF_TOKEN=${HF_TOKEN}
    command: python app.py